### ISSUE TITLE
After Java update the app doesn't run

### ISSUE THREAD

**Issue by kazerniel** [Drant/GW2Navi#1]
Today I've updated my Java to v8 update 131, and the app stopped  working. When I try to launch it, it gives this error:

> Windows cannot find 'javaw'. Make sure you typed the name correctly, and then try again.

My system is Win7 SP1 x64.

**Comment by Drant** [comment]
I downloaded and executed jre-8u131-windows-x64.exe; I proceeded with uninstalling previous Java versions when asked by the installer; immediately after finishing installation, I was able to launch GW2Navi_Start_2D.bat and GW2Navi_Start_3D.bat (Chromium version). For the IE version, I tried double clicking GW2Navi_Win64.jar and nothing happened, so I restarted my computer and now I am able to also run the IE version.

So please do these two things if you have not: Uninstall previous versions of Java before updating it, and restart your computer after installation.

**Comment by kazerniel** [comment]
Hi, I downloaded and installed the Java version you quoted (though the installer didn't ask me if I wanted to remove previous versions). Restarted my PC before and after the installation, but it still gives the same error. Btw I'm using the Chromium version of the app. (Also downloaded the newest release of it, just in case.)

**Comment by Drant** [comment]
Open GW2Navi_Start_2D.bat with a text editor and replace everything with:

@echo off
start "" "C:/Program Files/Java/jre1.8.0_131/bin/javaw.exe" -cp "bin/*;bin/GW2Navi_Win64.jar" -Djava.library.path=./bin/lib/libcef/win64 GW2Navi.Main

Basically, I replaced [start javaw] with [start "" PATH_TO_YOUR_javaw.exe], so modify that part if your directory is different.

**Comment by kazerniel** [comment]
That fixed it, thanks :)
